name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --build-arg PYTHON_VERSION=3.7 --tag hailbase:initial --file Dockerfile
    - name: Perform DH Login
      run: docker login -u ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}
    - name: Push New Image
      run: docker push rjbenikar/hailbase:initial
